version: '3.9'

services:
  ubuntu:
    build: .
    container_name: persistent_ubuntu
    hostname: persistent_ubuntu
    volumes:
      - ubuntu_data:/data
    network_mode: host
    restart: always
    tty: true
    stdin_open: true

volumes:
  ubuntu_data:
    driver: local