version: '3.9'

services:
  ubuntu:
    build: .
    container_name: persistent_ubuntu
    hostname: persistent_ubuntu
    volumes:
      - ubuntu_data:/data
    network_mode: host
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    network_mode: host
    restart: always

volumes:
  ubuntu_data:
    driver: local
  mysql_data:
    driver: local
